spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB


mybatis-plus:
  mapper-locations: classpath*:mapper/xml/*.xml
  type-aliases-package: com.edu.neu.zady.pojo
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      update-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: flag

healthlung:
  default-page-size: 10
  default-province: 北京
  default-city: 朝阳区

server:
  port: 8080
  servlet:
    context-path: /api/
